[character]
success_symbol = '[ğŸ‘»]()'
error_symbol = '[ğŸ¤”]()'
vimcmd_symbol = '[ğŸŸ¢]()'
vimcmd_replace_one_symbol = '[ğŸŸ¡]()'
vimcmd_replace_symbol = '[ğŸŸ ]()'
vimcmd_visual_symbol = '[ğŸŸ£]()'
